name: Build Exhxx VPN Core

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # تحديث إصدار Go ليتوافق مع أحدث المحركات

    # تنصيب أداة Gomobile وإضافتها لمسار النظام
    - name: Install Gomobile Translator
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    # تهيئة الأداة لربط محركات Go بنظام الأندرويد
    - name: Initialize Gomobile
      run: gomobile init

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build APK with Global Gradle
      run: gradle assembleDebug
      working-directory: V2rayNG

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Exhxx-VPN-Core-APK
        path: V2rayNG/app/build/outputs/apk/*/debug/*.apk
